language: node_js
node_js:
  - "4.3"
  - "6.7"
env:
  - NODE_ENV=test
script: "npm run-script cover-test"
services:
  - mongodb
after_script:
  - ./node_modules/.bin/codeclimate-test-reporter.cmd < ./coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run-script coverage-cleanup
addons:
  code_climate:
    repo_token: "bJN3F4/wVvKSC9lWjb2vM+m628F7nlV2ciVX+vfV2WbHy6ognDamop/J7+h/GKymwzgVoGGP/1iTMP37fywmIrOI6Jjc9ZCLZmHHUqKKnpFMwL7MJqd2jZx/WYtXQeQRF8UeEQbrK/ieA7Bt4baMdNIDysQ8tmYP/KBbeL9MOhfsX+4FdQT6Ruqns3bQB3zQHtnFg8lYQA5UgymAU/nu2/va6De7Yv0LQzFPjUaLTZyf9VwoUIts6PVBu0ChO7r4wwTQWVMb+Gepu6N6XB3EmacfepNE+e98t3R71IUHwapRsW7ZYKcJ3AW3B8jg0UWivr/1+lFEX2RJ9kXex8DKVWvL+zfWL9fmASx5VfbxgQL+Rs18irdXF2fy7OpGccVKRkpPDMht2LfRPv4aUQye+i3+09b6lu59b75rVGaYra9i8U844bTncCgw+0mq7+1iBNrJt+EMky8N33FeCS0ylrmzdnuJbxDBjEkV+iL8gNOoy89wvkUjpU+7IuiEHvtboCgQePX/JObb8NYzupo2oAKjHUjfzjjJlnpZCM8RHNw3u4vI3TBOWYAv8tGggGOO2pq1Qdkt3l1qLaJCiNfYcpK+cUg6eq+DFqEGvcXtHXRZ3GhP94b6IkF0xeU/w5msBkHlveN4wJBF39kbpIULFDsEAr1IzIkKq496ISTjHHw="
